// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/types/http.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// POKTHTTPRequest represents an http.Request to be serialized and sent to a RelayMiner
// by an Application/Gateway client within a RelayRequest payload.
type POKTHTTPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// method is the HTTP method/verb of the request. If it is a RESTful API, it
	// will be one of the following: GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD.
	// If it is a JSON-RPC API, it will be POST.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// header is a map of keys to multiple values belonging to the same key used
	// to group headers together, This is to avoid creating a new message type
	// that represents a single header key-values messages. Since protobuf does not
	// support `map<string, repeated string>`.
	Header map[string]*Header `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// url is the URL of the request. It is a string that represents the request's
	// URL with all its components (scheme, host, path, query, fragment).
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// body_bz is the body of the request in bytes. POKTHTTPRequest mimics
	// http.request with the difference that the body is a byte slice instead of
	// an io.readcloser, this is to avoid reading the io.readcloser each time
	// the body is needed.
	BodyBz        []byte `protobuf:"bytes,4,opt,name=body_bz,json=bodyBz,proto3" json:"body_bz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *POKTHTTPRequest) Reset() {
	*x = POKTHTTPRequest{}
	mi := &file_proto_types_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POKTHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POKTHTTPRequest) ProtoMessage() {}

func (x *POKTHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POKTHTTPRequest.ProtoReflect.Descriptor instead.
func (*POKTHTTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_types_http_proto_rawDescGZIP(), []int{0}
}

func (x *POKTHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *POKTHTTPRequest) GetHeader() map[string]*Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *POKTHTTPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *POKTHTTPRequest) GetBodyBz() []byte {
	if x != nil {
		return x.BodyBz
	}
	return nil
}

// POKTHTTPResponse represents an http.Response to be serialized and sent by a RelayMiner
// back to the Application/Gateway client within a RelayResponse payload.
type POKTHTTPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status_code is the HTTP status code of the response. If it is a RESTful API,
	// it will be one of the following: 200, 201, 204, 400, 401, 403, 404, 500.
	// If it is a JSON-RPC API, the status code will be 200 and any error will be
	// in the body of the response.
	StatusCode uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// header is a map of keys to multiple values belonging to the same key used
	// to group headers together, This is to avoid creating a new message type
	// that represents a header key-values message. Since protobuf does not
	// support `map<string, repeated string>`.
	Header map[string]*Header `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// body_bz is the body of the request in bytes. POKTHTTPResponse mimics
	// http.request with the difference that the body is a byte slice instead of
	// an io.readcloser, this is to avoid reading the io.readcloser each time
	// the body is needed.
	BodyBz        []byte `protobuf:"bytes,3,opt,name=body_bz,json=bodyBz,proto3" json:"body_bz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *POKTHTTPResponse) Reset() {
	*x = POKTHTTPResponse{}
	mi := &file_proto_types_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POKTHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POKTHTTPResponse) ProtoMessage() {}

func (x *POKTHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POKTHTTPResponse.ProtoReflect.Descriptor instead.
func (*POKTHTTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_types_http_proto_rawDescGZIP(), []int{1}
}

func (x *POKTHTTPResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *POKTHTTPResponse) GetHeader() map[string]*Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *POKTHTTPResponse) GetBodyBz() []byte {
	if x != nil {
		return x.BodyBz
	}
	return nil
}

// Header represents a single header key-values message.
// Since protobuf does not support map<string, repeated string>, we use this
// message to accurately represent a single http.Header key which could have multiple
// values.
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the header.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The values associated with the header key.
	Values        []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_types_http_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_http_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_types_http_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_types_http_proto protoreflect.FileDescriptor

const file_proto_types_http_proto_rawDesc = "" +
	"\n" +
	"\x16proto/types/http.proto\x12\tsdk.types\"\xe2\x01\n" +
	"\x0fPOKTHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12>\n" +
	"\x06header\x18\x02 \x03(\v2&.sdk.types.POKTHTTPRequest.HeaderEntryR\x06header\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x17\n" +
	"\abody_bz\x18\x04 \x01(\fR\x06bodyBz\x1aL\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.sdk.types.HeaderR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x10POKTHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12?\n" +
	"\x06header\x18\x02 \x03(\v2'.sdk.types.POKTHTTPResponse.HeaderEntryR\x06header\x12\x17\n" +
	"\abody_bz\x18\x03 \x01(\fR\x06bodyBz\x1aL\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.sdk.types.HeaderR\x05value:\x028\x01\"2\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06valuesB+Z)github.com/pokt-network/shannon-sdk/typesb\x06proto3"

var (
	file_proto_types_http_proto_rawDescOnce sync.Once
	file_proto_types_http_proto_rawDescData []byte
)

func file_proto_types_http_proto_rawDescGZIP() []byte {
	file_proto_types_http_proto_rawDescOnce.Do(func() {
		file_proto_types_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_http_proto_rawDesc), len(file_proto_types_http_proto_rawDesc)))
	})
	return file_proto_types_http_proto_rawDescData
}

var file_proto_types_http_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_types_http_proto_goTypes = []any{
	(*POKTHTTPRequest)(nil),  // 0: sdk.types.POKTHTTPRequest
	(*POKTHTTPResponse)(nil), // 1: sdk.types.POKTHTTPResponse
	(*Header)(nil),           // 2: sdk.types.Header
	nil,                      // 3: sdk.types.POKTHTTPRequest.HeaderEntry
	nil,                      // 4: sdk.types.POKTHTTPResponse.HeaderEntry
}
var file_proto_types_http_proto_depIdxs = []int32{
	3, // 0: sdk.types.POKTHTTPRequest.header:type_name -> sdk.types.POKTHTTPRequest.HeaderEntry
	4, // 1: sdk.types.POKTHTTPResponse.header:type_name -> sdk.types.POKTHTTPResponse.HeaderEntry
	2, // 2: sdk.types.POKTHTTPRequest.HeaderEntry.value:type_name -> sdk.types.Header
	2, // 3: sdk.types.POKTHTTPResponse.HeaderEntry.value:type_name -> sdk.types.Header
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_types_http_proto_init() }
func file_proto_types_http_proto_init() {
	if File_proto_types_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_http_proto_rawDesc), len(file_proto_types_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_http_proto_goTypes,
		DependencyIndexes: file_proto_types_http_proto_depIdxs,
		MessageInfos:      file_proto_types_http_proto_msgTypes,
	}.Build()
	File_proto_types_http_proto = out.File
	file_proto_types_http_proto_goTypes = nil
	file_proto_types_http_proto_depIdxs = nil
}
