name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  GKE_CLUSTER: protocol-us-central1
  GKE_ZONE: us-central1

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --timeout 20m --verbose

      - name: Test
        run: make test_all
